name: CMake on multiple platforms

on:
  push:
    branches: [ "testhtml" ]
  pull_request:
    branches: [ "testhtml" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-latest
          - windows-2019
          - windows-2022
        compiler:
          - { os-pattern: 'Ubuntu', name: 'gcc-11', install: 'g++-11' }
          - { os-pattern: 'Ubuntu', name: 'gcc-12', install: 'g++-12' }
          - { os-pattern: 'windows', name: 'msvc', install: '' }
          - { os-pattern: 'windows', name: 'mingw', install: 'mingw' }
        exclude:
          - os: ubuntu-20.04
            compiler: { os-pattern: 'windows' }
          - os: ubuntu-22.04
            compiler: { os-pattern: 'windows' }
          - os: ubuntu-latest
            compiler: { os-pattern: 'windows' }
          - os: windows-2019
            compiler: { os-pattern: 'Ubuntu' }
          - os: windows-2022
            compiler: { os-pattern: 'Ubuntu' }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: contains(matrix.os, 'Ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler.install }} cmake

    - name: Install dependencies (Windows)
      if: contains(matrix.os, 'windows')
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        if "${{ matrix.compiler.name }}" == "mingw" choco install mingw -y
      shell: cmd

    - name: Configure CMake
      run: |
        if [ "${{ matrix.compiler.name }}" == "mingw" ]; then
          cmake -S . -B build -G "MinGW Makefiles"
        else
          cmake -S . -B build
        fi
      shell: bash

    - name: Build
      run: |
        cmake --build build --config Release
      shell: bash

    - name: Run
      run: |
        if [ "${{ matrix.os }}" = "Ubuntu-20.04" ] || [ "${{ matrix.os }}" = "Ubuntu-22.04" ] || [ "${{ matrix.os }}" = "Ubuntu-latest" ]; then
          ./build/check_kit
        else
          if [ -f "build/Release/check_kit.exe" ]; then
            ./build/Release/check_kit.exe
          else
            ./build/Debug/check_kit.exe
          fi
        fi
      shell: bash
